name: Generate Snake and Push

on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: mohitjaiswal28
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Fetch recent push activity
      - name: Fetch recent push activity
        id: fetch-push-activity
        run: |
          # Fetch recent push activity using GitHub API
          echo "::set-output name=push_activity::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            'https://api.github.com/user/events?per_page=100' | jq -r '.[] | select(.type == "PushEvent") | .created_at')"

      # Show recent push activity for debugging
      - name: Show recent push activity
        run: |
          echo "${{ steps.fetch-push-activity.outputs.push_activity }}"

      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
